version: "3.0"

services:
  app:
    build: .
    image: hoinky-platform
    command: daphne -u /tmp/daphne.sock --bind 0.0.0.0 --port 8000 Hoinky.asgi:application
    env_file:
      - app.env
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://postgres:hoinky@postgres:5432/hoinkydb
      - DJANGO_SETTINGS_MODULE=Hoinky.settings
    expose:
      - 8000
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:12.0
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hoinkydb
      - POSTGRES_PASSWORD=hoinky
      
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    image: hoinky-nginx
    volumes:
      - ./static/:/app/static/
    ports:
      - "80:80"
    depends_on:
      - app
  
  redis:
    image: "redis:6.2"
    ports:
      - "6379:6379"

volumes:
  postgres-data:
