# Generated by Django 5.0.6 on 2024-07-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoinkyPass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoinkyuser',
            name='quests_achieved',
            field=models.ManyToManyField(blank=True, related_name='users', to='HoinkyPass.quest'),
        ),
    ]
